### ISSUE TITLE
Is bedtrap even good?

### ISSUE THREAD

**Issue by master7720** [PlutoSolutions/bedtrap-rip#12]

**Comment by EurekaEffect** [comment]
sure, thats why crackers fanning on me

**Comment by mr-nv** [comment]
same as all other paid meteor addons - 1.12 public modules just ported to 1.18 and sold for money

**Comment by EurekaEffect** [comment]
imagine

пт, 28 янв. 2022 г., 09:41 mr-nv ***@***.***>:

**Comment by mr-nv** [comment]
imagine what

пт, 28 янв. 2022 г., 10:48 Eureka ***@***.***>:

**Comment by master7720** [comment]
> same as all other paid meteor addons - 1.12 public modules just ported to 1.18 and sold for money

Ah

**Comment by EurekaEffect** [comment]
he didn't see the code and modules, what u talking about

пт, 28 янв. 2022 г., 10:26 PreparedSystem_32 ***@***.***>:

**Comment by Kiriyaga7615** [comment]
> same as all other paid meteor addons - 1.12 public modules just ported to 1.18 and sold for money

ало дебик пруфы кончено металлические, учитывая что ты даже код чекнуть не может, нищета блять

**Comment by EurekaEffect** [comment]
бамп

пт, 28 янв. 2022 г., 16:58 киригай ***@***.***>:

**Comment by mr-nv** [comment]
сажа

**Comment by master7720** [comment]
time to pull out google translate
