### ISSUE TITLE
new src when?🥵 

### ISSUE THREAD

**Issue by Vitalasy** [PlutoSolutions/bedtrap-rip#13]
🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵

**Comment by Vitalasy** [comment]
nice webhook utils tho.​‌​​​‌​​‌‌​‌​‌​​‌‌​‌​‌​​‌​​‌​​‌‌‌​​​​‌‌

**Comment by mr-nv** [comment]
>nice webhook utils tho.​‌​​​‌​​‌‌​‌​‌​​‌‌​‌​‌​​‌​​‌​​‌‌‌​​​​‌‌
yea when you run bedtrap it tries to send a message with your ip/hwid/name/etc to a webhook https://discord.com/api/webhooks/914600825869987861/jcpY1ZNDokBCJJLE73jo4yLA-WtIFyOZShOoNyNqCSUNP_01TVMAZWIRzLhFR55bpKyY
its already nuked to its not sending anything

**Comment by mr-nv** [comment]
bedtrap is obfuscated with bozar so no src
and why would you want src of that shit lol

**Comment by Vitalasy** [comment]
> bedtrap is obfuscated with bozar so no src and why would you want src of that shit lol

i want it for some disclosed reasons but ig i can't get it.
