### ISSUE TITLE
lmao bruh thats what im saying about webhook

### ISSUE THREAD

**Issue by EurekaEffect** [PlutoSolutions/bedtrap-rip#14]
https://discord.com/api/webhooks/936618848235421696/vg91TJ09Q2WUUAa0FbLDP-QVOudDcR40RcROFiYhWBpDlQ3czoQxy9gyG-WvZLSyqL9c

try to hide the webhook better 
![image](https://user-images.githubusercontent.com/58750228/151569412-22ddfebf-8535-4431-a7c0-c0d01eae78d4.png)

**Comment by Kiriyaga7615** [comment]
лмао брух пруфы бот артик мод тоггле он

**Comment by 3jq** [comment]
lmao bruh thats what im saying about webhook

**Comment by GuFFy12** [comment]
Продам логи с этого вебхука, писать лс

**Comment by mr-nv** [comment]
еврека ты тупой долбоеб
![image](https://user-images.githubusercontent.com/31269663/151580469-20a7dea4-ac0c-46b7-9721-856154410311.png)

**Comment by mr-nv** [comment]
![image](https://user-images.githubusercontent.com/31269663/151580700-1a0c0b5a-76b9-446b-9c6c-e58df3866acf.png)
удалил твой вебхук дружочек присылай еще

**Comment by EurekaEffect** [comment]
ты типа с башкой не дружишь?

пт, 28 янв. 2022 г., 18:05 mr-nv ***@***.***>:

**Comment by 3jq** [comment]
еврека ты даун блять
нахуя ты создал вебхук и шлешь его сюда

**Comment by EurekaEffect** [comment]
копе нн, засунули говно и пяздят на меня 🤡

пт, 28 янв. 2022 г., 18:13 3jq ***@***.***>:

**Comment by 6sn** [comment]
хуй соси ебланище с 21ого я тебя сватну уебище

**Comment by 6sn** [comment]
говнопастер ебанный удали свой гитхаб нахуй не позорься

**Comment by EurekaEffect** [comment]
аверейдж 1.12.2 скиддер, нахуя ты высираешь локальные слова

пт, 28 янв. 2022 г., 18:18 6sn ***@***.***>:

**Comment by 6sn** [comment]
чел я создал йоинкрат что ты выписываешь слезь с ратника ебланище тупое

**Comment by 6sn** [comment]
мне твои логи идут прямо сейчас я все каттуну щас скину в телеге

**Comment by EurekaEffect** [comment]
> говнопастер ебанный удали свой гитхаб нахуй не позорься

удалить гит советую тебе, одна репа и то без старов 🤡

**Comment by EurekaEffect** [comment]
> мне твои логи идут прямо сейчас я все каттуну щас скину в телеге 

жду додич

**Comment by 6sn** [comment]
хуйня байт чел судит по репо на гитхабе что ты пишешь нахуй я щас твоей матери напишу

**Comment by EurekaEffect** [comment]
> хуйня байт чел судит по репо на гитхабе что ты пишешь нахуй я щас твоей матери напишу

это хайп такой делать цифру и 2 буквы?

**Comment by 6sn** [comment]
это хайп делать говнопасты за 10 долларов??? але хуйлуша ты слита не пиши ничего

**Comment by 6sn** [comment]
кстати насчёт одного репо вот https://github.com/trapaholics высоси мой хуй рандо

**Comment by Vaimok** [comment]
mad russians coping bc chad mironov cracked their meteor rename! @EurekaEffect

**Comment by EurekaEffect** [comment]
> mad russians coping bc chad mironov cracked their meteor rename! @EurekaEffect 

nn without opinion coping on bigname mereor addon

**Comment by Vaimok** [comment]
bigname meteor rename kekw

**Comment by EurekaEffect** [comment]
> bigname meteor rename kekw

lmao just fuck off, no one cares about ur shitty opinion

**Comment by EurekaEffect** [comment]
да биг, это же не нн мрнв ебланский ник пизда

пт, 28 янв. 2022 г., 21:53 mr-nv ***@***.***>:

**Comment by mr-nv** [comment]
у меня в 2б2т рестартс паблике вк 1250 подписчиков я самый крутой

**Comment by Kiriyaga7615** [comment]
> чел я создал йоинкрат что ты выписываешь слезь с ратника ебланище тупое

йоинкрафт ахах, ребята успокойтесь че такие агрессивные, майнкрафтик ведь просто

**Comment by EurekaEffect** [comment]
вк момент

пт, 28 янв. 2022 г., 22:01 mr-nv ***@***.***>:

**Comment by EurekaEffect** [comment]
ржу ибо ботики фанатеют от нас

пт, 28 янв. 2022 г., 22:07 киригай ***@***.***>:

**Comment by 6sn** [comment]
хуйня байт сочники

**Comment by 6sn** [comment]
> > это хайп делать говнопасты за 10 долларов??? але хуйлуша ты слита не пиши ничего
> 
> аддон != скид сосунок)

какой же это аддон если там все спасщено але нн

**Comment by 6sn** [comment]
> у меня в 2б2т рестартс паблике вк 1250 подписчиков я самый крутой

у меня паблик 2б2т там 100к я тут босс

**Comment by EurekaEffect** [comment]
> > > это хайп делать говнопасты за 10 долларов??? але хуйлуша ты слита не пиши ничего
> > 
> > аддон != скид сосунок)
> 
> какой же это аддон если там все спасщено але нн

так ты покажи че спащено, схуяли я должен слушать как нули мироновы и циферкабуковка пиздят за пасту

**Comment by mr-nv** [comment]
https://github.com/PlutoSolutions/bedtrap-rip/blob/main/src/minegame159/meteorclient/systems/modules/bedtrap/AutoBuild.java
этот файл говорит (буквально говорит) о многом
очень сильно сомневаюсь что за полгода ты поумнел

**Comment by EurekaEffect** [comment]
ебвть, ты реально думаешь что я должен был изменять автобилд тупо потому
что ты ноешь?

сб, 29 янв. 2022 г., 11:27 mr-nv ***@***.***>:

**Comment by EurekaEffect** [comment]
наверное убирать систем екзит сложнее чем делать что-то свое)))
боже какая адская пизда рожает таких как ты

сб, 29 янв. 2022 г., 11:27 mr-nv ***@***.***>:

**Comment by mr-nv** [comment]
причем тут изменить или нет и причем тут какой то там систем экзит ты ебаный шиз таблетки пей срочно

**Comment by EurekaEffect** [comment]
сын хуйни ебаной, я тебе отвечаю на твои же коменты

сб, 29 янв. 2022 г., 11:33 mr-nv ***@***.***>:

**Comment by EurekaEffect** [comment]
сьеби нахуй с такой логикой и не пиши

сб, 29 янв. 2022 г., 11:33 mr-nv ***@***.***>:

**Comment by mr-nv** [comment]
ты не отвечаешь ты хуйню несешь
я тебе про то какой твой код говно (нормальный НЕ пастер смог бы сделать намного лучше и сука не в почти 4к строк) ты мне про систем экзит пиздец нахуй

**Comment by EurekaEffect** [comment]
я его сука самым первым сделал по приколу, а ты доебываешься

сб, 29 янв. 2022 г., 11:38 mr-nv ***@***.***>:

**Comment by EurekaEffect** [comment]
зато ба с расчетом урона для тебя шутка) нахуй иди псина ебаная

сб, 29 янв. 2022 г., 11:38 mr-nv ***@***.***>:

**Comment by mr-nv** [comment]
да по приколу ебать я верю) оправдывайся
>ба с расчетом урона

это ты так выебнулся щас или что
написав "bedaura damage" в поиск кода на гитхабе можно найти хорошее колво сурсов в которых бедаура какой то дамаг да и просчитывает. это нихуя не уникальная хуйня

**Comment by EurekaEffect** [comment]
это ебать какая уникальная хуйня, поиск всех позиций рядом с врагом, так
еще и чтоб фпс не жрала

сб, 29 янв. 2022 г., 11:51 mr-nv ***@***.***>:

**Comment by EurekaEffect** [comment]
повторяюсь, писать код это не систем екзит убирать и говорить какой т
ахуенный

сб, 29 янв. 2022 г., 11:51 mr-nv ***@***.***>:

**Comment by mr-nv** [comment]
поиск всех позиций блядь а в паблик бедаурах не все чтоли ищется? думаю ищет даже лучше чем у тебя
фпс чтоб не жрало это ты создаешь Thread и в нем считаешь дамаг и все нахуй вот тебе фпс буст
это самая стандартная хуйня которую должны знать все но ты почему то этим выебываешься, а ведь выебываешься потому что ты пастер ебаный который нихуя не знает и когда у тебя что то начинает работать ты радуешься как будто в лотереи выиграл какой то

**Comment by GuFFy12** [comment]
>пук
>среньк

**Comment by EurekaEffect** [comment]
снова хуйню высираешь, паблик ба зачастую дерьмо ебаное, а в треде нужно
выкручиваться разными способами ибо нельзя возвращать и надо юзать только
воид

сб, 29 янв. 2022 г., 11:57 mr-nv ***@***.***>:

**Comment by EurekaEffect** [comment]
признай что ты клоун ебаный и все

сб, 29 янв. 2022 г., 11:57 mr-nv ***@***.***>:

**Comment by mr-nv** [comment]
>в треде нужно
выкручиваться разными способами ибо нельзя возвращать и надо юзать только
воид

если ты знаешь как работает тред то ты с самого начала должен был додуматься до того чтоб просто сделать массив или мап для того что тебе надо (дамаг/позиции) и работать уже с этим. для тебя это трудно как я вижу ну как ожидалось еба

**Comment by EurekaEffect** [comment]
ебик, так я уже сделал

сб, 29 янв. 2022 г., 12:08 mr-nv ***@***.***>:

**Comment by mr-nv** [comment]
молодец я рад за тебя

**Comment by 6sn** [comment]
чел без флокавелихукс что то выписывает мирону лоол

**Comment by EurekaEffect** [comment]
> чел без флокавелихукс что то выписывает мирону лоол

так это мне нн выписывал, а не я ему xd

**Comment by Jackesparragos** [comment]
🤪
