### ISSUE TITLE
хрюкни пятистрочный xd

### ISSUE THREAD

**Issue by EurekaEffect** [PlutoSolutions/bedtrap-rip#7]

**Comment by oyzipfile** [comment]
чет порвался ты, 4к строк в билдере, недопастер

**Comment by EurekaEffect** [comment]
> чет порвался ты, 4к строк в билдере, недопастер

написал еблоид, который кидал в дс гулага скид кроноса с токенлогом без блять обфускации, удались с югейма нн

**Comment by oyzipfile** [comment]
я слит братан...............

**Comment by cattyngmd** [comment]
> > чет порвался ты, 4к строк в билдере, недопастер
> 
> написал еблоид, который кидал в дс гулага скид кроноса с токенлогом без блять обфускации, удались с югейма нн

не ну жобф конечно лучше
